variables:
  - template: /eng/common-variables.yml
  - name: Build.Repository.Clean
    value: true

trigger:
  batch: true
  branches:
    include:
    - maint/*
    - release/*

pr:
  branches:
    include:
    - maint/*
    - release/*

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      variables:
        - _BuildConfig: Release
      jobs:

      ############ BROWSER BUILD ############
      - job: Build_Browser
        displayName: Browser
        timeoutInMinutes: 30
        pool:
          vmImage: ubuntu-16.04
        container:
          image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-webassembly-20210111135621-8ac9b02
        steps:
        - bash: |
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Browser /p:TargetArchitecture=wasm $(_InternalBuildArgs)
          displayName: Build
        - task: PublishPipelineArtifact@1
          displayName: Upload artifacts
          inputs:
            targetPath: 'artifacts/bin'
            artifactName: Artifacts_Browser
            condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ iOS BUILD ############
      - job: Build_iOS
        displayName: iOS
        timeoutInMinutes: 45
        pool:
          vmImage: macOS-10.15
        steps:
        - bash: |
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOSSimulator /p:TargetArchitecture=x64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOSSimulator /p:TargetArchitecture=x86 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOSSimulator /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOS /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOS /p:TargetArchitecture=arm $(_InternalBuildArgs)
            ### delete this entry after https://github.com/dotnet/runtime/pull/49305 is merged ##
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOS /p:TargetArchitecture=x64 $(_InternalBuildArgs)
            ### delete this entry after https://github.com/dotnet/runtime/pull/49305 is merged ##
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOS /p:TargetArchitecture=x86 $(_InternalBuildArgs)
          displayName: Build
        - task: PublishPipelineArtifact@1
          displayName: Upload artifacts
          inputs:
            targetPath: 'artifacts/bin'
            artifactName: Artifacts_iOS
            condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ tvOS BUILD ############
      - job: Build_tvOS
        displayName: tvOS
        timeoutInMinutes: 30
        pool:
          vmImage: macOS-10.15
        steps:
        - bash: |
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOSSimulator /p:TargetArchitecture=x64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOSSimulator /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOS /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
            ### delete this entry after https://github.com/dotnet/runtime/pull/49305 is merged ##
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOS /p:TargetArchitecture=x64 $(_InternalBuildArgs)
          displayName: Build
        - task: PublishPipelineArtifact@1
          displayName: Upload artifacts
          inputs:
            targetPath: 'artifacts/bin'
            artifactName: Artifacts_tvOS
            condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ Android BUILD ############
      - job: Build_Android
        displayName: Android
        timeoutInMinutes: 30
        pool:
          vmImage: ubuntu-16.04
        container:
          image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-android-20200422191843-e2c3f83
        steps:
        - bash: |
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=x64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=x86 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
            ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=arm $(_InternalBuildArgs)
          displayName: Build
        - task: PublishPipelineArtifact@1
          displayName: Upload artifacts
          inputs:
            targetPath: 'artifacts/bin'
            artifactName: Artifacts_Android
            condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))

      ############ PACK AND PUBLISH ############
      - job: Publish_Packages
        displayName: Publish packages
        condition: and(succeeded(), ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest'))
        dependsOn:
          - Build_Browser
          - Build_iOS
          - Build_tvOS
          - Build_Android
        timeoutInMinutes: 30
        pool:
          vmImage: windows-2019
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Artifacts_Browser
            path: 'artifacts/bin'
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Artifacts_iOS
            path: 'artifacts/bin'
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Artifacts_tvOS
            path: 'artifacts/bin'
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Artifacts_Android
            path: 'artifacts/bin'
        - powershell: |
            .\eng\common\build.ps1 -ci -restore -pack -publish -configuration $(_BuildConfig) -projects $(Build.SourcesDirectory)\eng\icu.proj /p:PackOnly=true $(_InternalBuildArgs)
          displayName: Pack and Publish packages

############ POST BUILD ARCADE LOGIC ############
- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/post-build/post-build.yml
    parameters:
      publishingInfraVersion: 3
      enableSourceLinkValidation: false
      enableSigningValidation: false
      enableSymbolValidation: false
      enableNugetValidation: true
