variables:
  - template: /eng/common-variables.yml@self
  - template: /eng/common/templates-official/variables/pool-providers.yml@self
  - name: Codeql.Enabled  # TODO: split codeql into separate pipeline
    value: true
  - name: LinuxImage
    value: 1es-ubuntu-2204
  - name: WindowsImage
    value: 1es-windows-2022
  - name: MacImage
    value: macOS-12

trigger:
  batch: true
  branches:
    include:
    - dotnet/main
    - dotnet/release/*

pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      tsa:
        enabled: true
      policheck:
        enabled: true
        exclusionsFile: $(Build.SourcesDirectory)\.config\PoliCheckExclusions.xml
      binskim:
        scanOutputDirectoryOnly: true
    pool:
      name: $(DncEngInternalBuildPool)
      image: $(WindowsImage)
      os: windows
    containers:
      mariner2crossamd64: 
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
      ubuntu2004wasi:
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-webassembly-net8-20230327150037-4404b5c
      ubuntu1804android:
        image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-android-20220131172314-3983b4e
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enablePublishBuildArtifacts: true
          enablePublishBuildAssets: true
          enablePublishUsingPipelines: true
          jobs:

          ############ BROWSER BUILD ############
          - job: Build_Browser
            displayName: Browser
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(LinuxImage)
              os: linux
            container: mariner2crossamd64
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Browser /p:TargetArchitecture=wasm $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_Browser

          - job: Build_Browser_Threading
            displayName: Browser_Threading
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(LinuxImage)
              os: linux
            container: mariner2crossamd64
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:WasmEnableThreads=true $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_Browser_Threading

          ############ WASI BUILD ############
          - job: Build_Wasi
            displayName: Wasi
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(LinuxImage)
              os: linux
            container: ubuntu2004wasi
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Wasi /p:TargetArchitecture=wasm $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_Wasi

          - job: Build_Wasi_Threading
            displayName: Wasi_Threading
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(LinuxImage)
              os: linux
            container: ubuntu2004wasi
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Wasi /p:TargetArchitecture=wasm /p:WasmEnableThreads=true $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_Wasi_Threading

          ############ iOS BUILD ############
          - job: Build_iOS
            displayName: iOS
            timeoutInMinutes: 360
            pool:
              name: Azure Pipelines
              image: $(MacImage)
              os: macOS
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOSSimulator /p:TargetArchitecture=x64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOSSimulator /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=iOS /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_iOS

          ############ MacCatalyst BUILD ############
          - job: Build_MacCatalyst
            displayName: MacCatalyst
            timeoutInMinutes: 360
            pool:
              name: Azure Pipelines
              image: $(MacImage)
              os: macOS
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=MacCatalyst /p:TargetArchitecture=x64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=MacCatalyst /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_MacCatalyst

          ############ tvOS BUILD ############
          - job: Build_tvOS
            displayName: tvOS
            timeoutInMinutes: 360
            pool:
              name: Azure Pipelines
              image: $(MacImage)
              os: macOS
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOSSimulator /p:TargetArchitecture=x64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOSSimulator /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=tvOS /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_tvOS

          ############ Android BUILD ############
          - job: Build_Android
            displayName: Android
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(LinuxImage)
              os: linux
            container: ubuntu1804android
            steps:
            - bash: |
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=x64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=x86 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=arm64 $(_InternalBuildArgs)
                ./build.sh --ci --restore --build --configuration $(_BuildConfig) /p:TargetOS=Android /p:TargetArchitecture=arm $(_InternalBuildArgs)
              displayName: Build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)/artifacts/bin
                artifactName: Artifacts_Android

          ############ PACK AND PUBLISH ############
          - job: Publish_Packages
            displayName: Publish packages
            dependsOn:
            - Build_Browser
            - Build_Browser_Threading
            - Build_Wasi
            - Build_Wasi_Threading
            - Build_iOS
            - Build_MacCatalyst
            - Build_tvOS
            - Build_Android
            timeoutInMinutes: 360
            pool:
              name: $(DncEngInternalBuildPool)
              image: $(WindowsImage)
              os: windows
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_Browser
                path: 'artifacts/bin'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_Browser_Threading
                path: 'artifacts/bin/browser-threading'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_Wasi
                path: 'artifacts/bin'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_Wasi_Threading
                path: 'artifacts/bin/wasi-threading'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_iOS
                path: 'artifacts/bin'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_MacCatalyst
                path: 'artifacts/bin'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_tvOS
                path: 'artifacts/bin'
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: Artifacts_Android
                path: 'artifacts/bin'
            - powershell: |
                .\eng\common\build.ps1 -ci -restore -pack -publish -configuration $(_BuildConfig) -projects $(Build.SourcesDirectory)\eng\icu.proj /p:PackOnly=true $(_InternalBuildArgs)
              displayName: Pack and Publish packages

    ############ POST BUILD ARCADE LOGIC ############
    - template: /eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        enableSourceLinkValidation: false
        enableSigningValidation: false
        enableSymbolValidation: false
        enableNugetValidation: true
